### PR TITLE
The autoload file is not in the same directory

### PR DESCRIPTION
**Pull request by cmodijk**
Fixes #1
Copy/past from; https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L30-L36

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@cafferata  @cmodijk 👍

**Comment by ceesvanegmond** [comment]
New tag?

**Comment by cmodijk** [comment]
Yes, just created!

**Comment by ceesvanegmond** [comment]
👍

**Pull request merged**
