### PR TITLE
Feature: Don't forget to dump-autoload the repository

### PR DESCRIPTION
**Pull request by ceesvanegmond**
Feature: Don't forget to dump-autoload the repository

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
When following the installation guide, there’s one thing thats missing. The main file requires vendor/autoload.php which doesnt exist yet. Thats why the dump-autoload is needed.

**Comment by cmodijk** [comment]
I just installed it without this

**Comment by ceesvanegmond** [comment]
@cmodijk Tried again here. Same problem (see attachment).
schermafbeelding_2017-11-15_om_10_00_41

Vendors aren't there yet -> https://github.com/JCID/sourcetree-custom-action-gitlab-merge-request-opener/blob/master/sourcetree-merge-request-opener#L4

**Comment by cmodijk** [comment]
The problem is not that the autoload is not dump yet in your screen it stated that it is dumped but for the global installation the file is at a different location i just created #3

**Pull request closed without merging**
